crypto-platform/crypto-platform/crypto_platform/site/views.py
"""
Routes and views for the flask application.
"""

from flask import Blueprint, render_template
from datetime import datetime

from crypto_platform import connect

site = Blueprint('site', __name__,
                 template_folder='templates',
                 static_folder='static')

@site.route('/')
@site.route('/home')
def home():
    """Renders the home page."""
    return render_template(
        'index.html',
        title='Home Page',
        year=datetime.now().year
    )

@site.route('/coinbase_login')
def coinbase_login():
    return connect.coinbase_login()

crypto-platform/crypto-platform/crypto_platform/site/templates/index.html
<!DOCTYPE html><!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Mon Apr 11 2022 02:11:38 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="624610bcb949bcfc2676545d" data-wf-site="624610bcb949bc3118765456">

<head>
    <meta charset="utf-8">
    <title>Crypto Platform</title>
    <meta content="Incredible is a template, that combines a minimal modern design with the right amount of features to help you create an outstanding web for your business in no time." name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Webflow" name="generator">
    <link href="{{ url_for('.static', filename='css/normalize.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('.static', filename='css/webflow.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('.static', filename='css/cryptoproj.webflow.css') }}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">WebFont.load({ google: { families: ["Oswald:200,300,400,500,600,700", "Droid Sans:400,700", "Roboto:300,regular,500"] } });</script>
    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">!function (o, c) { var n = c.documentElement, t = " w-mod-"; n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch") }(window, document);</script>
    <link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="images/webclip.png" rel="apple-touch-icon">
</head>

<body class="body">
    <div data-collapse="medium" data-animation="default" data-duration="400" data-no-scroll="1" data-easing="ease" data-easing2="ease" role="banner" class="left-navigation w-nav">
        <a href="#" class="logo-link w-nav-brand">
            <h1 class="brand-text">CryptoPlatform</h1>
        </a>
        <nav role="navigation" class="nav-menu w-nav-menu">
            <a href="#home" data-w-id="59ba5dc3-83f7-6e1e-fb07-91533dbe48c8" class="nav-link w-nav-link">Home</a>
            <a href="#investing" class="nav-link w-nav-link">investing</a>
            <a href="#taxlossharvesting" class="nav-link w-nav-link">tax-loss harvesting</a>
            <a href="#contactus" class="nav-link w-nav-link">contact us</a>
        </nav>
        <div class="hamburger-button w-nav-button" style="-webkit-user-select: text;" aria-label="menu" role="button" tabindex="0" aria-controls="w-nav-overlay-0" aria-haspopup="menu" aria-expanded="false">
            <div class="w-icon-nav-menu"></div>
        </div>
        <div class="social-footer w-hidden-medium w-hidden-small w-hidden-tiny"></div>
        <div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0" style="display: none;"></div>
    </div>
    <div class="content">

        <!--Home-->
        <div id="home" class="banner">
            <div class="hero-title-wrapper">
                <h1 class="hero-heading">welcome to smarter investing</h1>
                <div class="hero-subheading">Hands-off cryptocurrency investments with tax-loss harvesting.</div>
                <div>
                    <a href="{{ url_for('site.coinbase_login') }}" class="hollow-button red" style="width: 400px; font-size: 20px">Connect to Coinbase to get Started</a>
                </div>
            </div>
        </div>

        <!--Investing-->
        <section id="investing" class="section wf-section">
            <div class="w-container">
                <div class="section-title-group">
                    <h2 class="section-heading centered">investing</h2>
                    <div class="section-subheading center">You can invest in a variety of professionally curated baskets.</div>
                </div>
                <div class="w-row">
                    <div class="column-0-padding w-col w-col-3" style="border-left: 3px solid #cccccc; ">
                        <img src="" width="100" alt="" class="grid-image">
                        <h3>Test Basket</h3>
                        <p>Comprised of the following:<br><br>Bitcoin<br>Ethereum<br><br>Basket for testing.</p>
                    </div>
                    <div class="column-0-padding w-col w-col-3" style="border-left: 3px solid #cccccc; ">
                        <img src="" width="100" alt="" class="grid-image">
                        <h3>Test Basket 2</h3>
                        <p>Comprised of the following:<br><br>Bitcoin<br>Ethereum<br>Ada.<br><br>Another basket for testing.</p>
                    </div>
                    <div class="column-0-padding w-col w-col-3" style="border-left: 3px solid #cccccc; ">
                        <img src="" width="100" alt="" class="grid-image">
                        <h3>Test Basket 3</h3>
                        <p>Comprised of the following:<br><br>Bitcoin<br>Ethereum<br>Litecoin<br>Ada.<br><br>Yet another basket for testing.</p>
                    </div>
                    <div class="column-0-padding w-col w-col-3" style="border-left: 3px solid #cccccc; ">
                        <img src="" width="100" alt="" class="grid-image">
                        <h3>basket 4</h3>
                        <p>Comprised of the following:<br><br>Bitcoin<br>Ethereum<br>Ethereum Classic.<br><br>This is our best performing basket.</p>
                    </div>
                </div>
            </div>
        </section>

        <!--Tax-loss Harvesting-->
        <section id="taxlossharvesting" class="section wf-section">
            <div class="w-container">
                <div class="section-title-group">
                    <h2 class="section-heading centered">tax-loss harvesting</h2>
                    <div class="section-subheading center">Your cryptocurrency investments can be tax-loss harvested for tax savings!</div>
                </div>
            </div>
        </section>

        <!--Call to Action-->
        <section class="call-to-action-section wf-section">
            <div class="container w-container">
                <div class="w-row">
                    <div class="w-col w-col-8">
                        <h3 class="call-to-action-heading">Connect to Coinbase to get started!</h3>
                    </div>
                    <div class="align-right w-col w-col-4">
                        <a href="#home" class="hollow-button white">Connect to Coinbase</a>
                    </div>
                </div>
            </div>
        </section>

        <!--Contact Us-->
        <section id="contactus" class="section section-gray wf-section">
            <div class="w-container">
                <div class="section-title-group">
                    <h2 class="section-heading centered">Contact Form</h2>
                    <div class="section-subheading center">Need to submit a concern or suggestion for the platform?</div>
                </div>
                <div class="form-wrapper squeezed w-form">
                    <form id="email-form" name="email-form" data-name="Email Form" method="get">
                        <div class="w-row">
                            <div class="column-remove-padding w-col w-col-6"><input type="text" class="form-field w-input" maxlength="256" name="name-7" data-name="Name 7" placeholder="Name" id="name-7"></div>
                            <div class="column-remove-padding w-col w-col-6"><input type="email" class="form-field w-input" maxlength="256" name="email-9" data-name="Email 9" placeholder="Email" id="email-9" required=""></div>
                        </div><textarea id="field-4" name="field-4" placeholder="Contact us for any platform issues, concerns, suggestions, etc." maxlength="5000" data-name="Field 4" class="form-field text-area w-input"></textarea><input type="submit" value="Send Message" data-wait="Please wait..." class="button full-width w-button">
                    </form>
                    <div class="success-message w-form-done">
                        <p class="paragraph-form">Thank you! Your submission has been received!</p>
                    </div>
                    <div class="success-message w-form-fail">
                        <p class="paragraph-form">Oops! Something went wrong while submitting the form :(</p>
                    </div>
                </div>
            </div>
        </section>

        <footer class="footer center wf-section">
            <div class="w-container">
                <div class="footer-text">Isaac Hopf | Stephen Kauk | Blake Merrill | Sheldon Silen</div>
            </div>
        </footer>

    </div>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=624610bcb949bc3118765456" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{{ url_for('.static', filename='scripts/webflow.js') }}" type="text/javascript"></script>
    <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>